### ISSUE TITLE
Uncaught TypeError: Property 'onbeforeunload' of object [object DOMWindow] is not a function

### ISSUE THREAD

**Issue by binarykitchen** [gustavnikolaj/before-unload#6]
Seeing that error with this user agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36

**Comment by gustavnikolaj** [comment]
There is no places in the source code where `window.onbeforeunload` is accessed as a property or called as a function. I only attach listeners to window for that event.

Could you describe what you were doing when encountering this error?

A stack trace or a code example would be really useful to understand what happened.

**Comment by binarykitchen** [comment]
Don't have a stack trace, I am afraid. Will add a source map to that minified code one day.

Looked at other places in my app and can't see where `onbeforeunload` is accessed. Browserify seems to do something but not sure about that.

Let's close this but keep an eye on it.

**Comment by gustavnikolaj** [comment]
Sure, let me know if I can be of any assistance!
